name: Test
on: [push]
jobs:
    Pytest:
        runs-on: ubuntu-focal
        strategy:
            matrix:
                python-version: ["3.9", "3.11"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
                cache: 'pip'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install "cython<3.0.0" 
                pip install -r requirements.txt
            - name: Test with pytest
              run: |
                pip install pytest pytest-cov
                cd simulation
                pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    